events {
  worker_connections 1024;
}

http {
  upstream api {
    server api:3000;
  }

  server {
    listen 80;
    location / {
      return 301 https://$host$request_uri;
    }
  }

  server {
    listen 443 ssl;
    ssl_certificate     /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;

    location /api/ {
      proxy_pass http://api/api/;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Proto https;
    }

    location /health {
      proxy_pass http://api/api/health;
    }
  }
}
