export type PilotAlertSeed = {
  id: string;
  type: 'at_risk' | 'approval_needed' | 'recovery_win';
  title: string;
  body: string;
  relativeTime: string;
  severity: 'red' | 'amber' | 'green';
  ctaLabel: string | null;
  ctaRoute: string | null;
  /** Roles that should see this alert */
  visibleToRoles: string[];
  institutionId: string;
};

const PES = '00000000-0000-4000-8000-000000000001';

/** Prototype screen 13 — alert inbox */
export const PILOT_ALERTS: PilotAlertSeed[] = [
  {
    id: '80000000-0000-4000-8000-000000000001',
    type: 'at_risk',
    title: '⚠ At-risk alert',
    body: 'Farhan A: attendance 68%, CO3 mastery below 30. Intervention plan drafted.',
    relativeTime: '9 min ago',
    severity: 'red',
    ctaLabel: 'Review plan →',
    ctaRoute: '/campus-drive',
    visibleToRoles: ['faculty', 'tpo', 'principal', 'admin'],
    institutionId: PES,
  },
  {
    id: '80000000-0000-4000-8000-000000000002',
    type: 'approval_needed',
    title: '✓ Approval needed',
    body: 'BCS304 IA-2 paper generated by Prof. Rao — awaiting moderation sign-off.',
    relativeTime: '1 hr ago',
    severity: 'amber',
    ctaLabel: 'Approve →',
    ctaRoute: '/paper-craft',
    visibleToRoles: ['moderator', 'principal', 'admin'],
    institutionId: PES,
  },
  {
    id: '80000000-0000-4000-8000-000000000003',
    type: 'recovery_win',
    title: '★ Recovery win',
    body: '6 students moved from at-risk to on-track this week after intervention plans.',
    relativeTime: 'Yesterday',
    severity: 'green',
    ctaLabel: null,
    ctaRoute: null,
    visibleToRoles: ['tpo', 'principal', 'admin'],
    institutionId: PES,
  },
];
